; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
build_flags = 
	-DCONFIG_BT_ENABLED=y
	-DCONFIG_BLE_MESH=y
	-DCONFIG_ESP_TLS_USING_MBEDTLS=1
	-DEXTRA_COMPONENT_DIRS=components/esp_idf_lib_helpers/
	-I${PROJECT_DIR}/include
	#build_flags =
    #-I$PROJECT_DIR/lib/esp-idf-lib/components
	#-I$PROJECT_DIR/pio/libdeps/esp32dev/esp-idf-lib/components
	#-Wno-unused-variable
	#-I./components
lib_deps = 
    https://github.com/jrowberg/i2cdevlib.git
	#mbed-syundo0730/I2Cdev@0.0.0+sha.3aa973ebe3e5
upload_speed = 921600
