; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200

 

build_flags =
    -DCONFIG_BT_ENABLED=y
    -DCONFIG_BLE_MESH=y
    -DCONFIG_ESP_TLS_USING_MBEDTLS=1
    -DEXTRA_COMPONENT_DIRS=components/esp-idf-lib/components
    -I${PROJECT_DIR}/include
    -Wno-unused-variable

lib_deps =
    https://github.com/UncleRus/esp-idf-lib
    https://github.com/espressif/arduino-esp32.git

upload_speed = 921600